=== ministryofjustice/laa-data-claims-api/claims-data/service/src/main/resources/schemas/LSCSMSBulkLoadSchemaV3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/"
        elementFormDefault="qualified"
        version="3.0">

    <xs:annotation>
        <xs:documentation>
            LSCSMS Bulk Load XML Schema
            --------------------------------
            Schema Version: V3 (Technical version: 3.0)
            Release Date: 2025-02-18
            Status: Current

            Summary:
            LAA Data Claims – bulk load submission format.
            Validates structure: submission → office → schedule → outcome/newMatterStarts/immigrationCLR.
            Business rules (e.g. date logic) are enforced by the application.

            Providers must validate against the latest published version.
        </xs:documentation>
    </xs:annotation>

    <!-- ========================= -->
    <!-- Simple Types (attributes) -->
    <!-- ========================= -->
    <xs:simpleType name="officeAccountNumber">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{6}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="submissionPeriod">
        <xs:restriction base="xs:string">
            <xs:pattern value="(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)-[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="areaOfLaw">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MEDIATION"/>
            <xs:enumeration value="CRIME LOWER"/>
            <xs:enumeration value="LEGAL HELP"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="scheduleNumber">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20"/>
            <xs:pattern value="[A-Za-z0-9/]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="upperSnake">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9_]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="outcomeItemName">
        <xs:restriction base="xs:string">
            <xs:enumeration value="FEE_CODE"/>
            <xs:enumeration value="CASE_REF_NUMBER"/>
            <xs:enumeration value="CASE_START_DATE"/>
            <xs:enumeration value="CASE_ID"/>
            <xs:enumeration value="CASE_STAGE_LEVEL"/>
            <xs:enumeration value="UFN"/>
            <xs:enumeration value="PROCUREMENT_AREA"/>
            <xs:enumeration value="ACCESS_POINT"/>
            <xs:enumeration value="CLIENT_FORENAME"/>
            <xs:enumeration value="CLIENT_SURNAME"/>
            <xs:enumeration value="CLIENT_DATE_OF_BIRTH"/>
            <xs:enumeration value="UCN"/>
            <xs:enumeration value="CLA_REF_NUMBER"/>
            <xs:enumeration value="CLA_EXEMPTION"/>
            <xs:enumeration value="GENDER"/>
            <xs:enumeration value="ETHNICITY"/>
            <xs:enumeration value="DISABILITY"/>
            <xs:enumeration value="CLIENT_POST_CODE"/>
            <xs:enumeration value="WORK_CONCLUDED_DATE"/>
            <xs:enumeration value="ADVICE_TIME"/>
            <xs:enumeration value="TRAVEL_TIME"/>
            <xs:enumeration value="WAITING_TIME"/>
            <xs:enumeration value="PROFIT_COST"/>
            <xs:enumeration value="VALUE_OF_COSTS"/>
            <xs:enumeration value="DISBURSEMENTS_AMOUNT"/>
            <xs:enumeration value="COUNSEL_COST"/>
            <xs:enumeration value="DISBURSEMENTS_VAT"/>
            <xs:enumeration value="TRAVEL_WAITING_COSTS"/>
            <xs:enumeration value="VAT_INDICATOR"/>
            <xs:enumeration value="LONDON_NONLONDON_RATE"/>
            <xs:enumeration value="CLIENT_TYPE"/>
            <xs:enumeration value="TOLERANCE_INDICATOR"/>
            <xs:enumeration value="TRAVEL_COSTS"/>
            <xs:enumeration value="OUTCOME_CODE"/>
            <xs:enumeration value="LEGACY_CASE"/>
            <xs:enumeration value="CLAIM_TYPE"/>
            <xs:enumeration value="ADJOURNED_HEARING_FEE"/>
            <xs:enumeration value="TYPE_OF_ADVICE"/>
            <xs:enumeration value="POSTAL_APPL_ACCP"/>
            <xs:enumeration value="SCHEDULE_REF"/>
            <xs:enumeration value="CMRH_ORAL"/>
            <xs:enumeration value="CMRH_TELEPHONE"/>
            <xs:enumeration value="AIT_HEARING_CENTRE"/>
            <xs:enumeration value="SUBSTANTIVE_HEARING"/>
            <xs:enumeration value="HO_INTERVIEW"/>
            <xs:enumeration value="HO_UCN"/>
            <xs:enumeration value="TRANSFER_DATE"/>
            <xs:enumeration value="DETENTION_TRAVEL_WAITING_COSTS"/>
            <xs:enumeration value="DELIVERY_LOCATION"/>
            <xs:enumeration value="PRIOR_AUTHORITY_REF"/>
            <xs:enumeration value="JR_FORM_FILLING"/>
            <xs:enumeration value="ADDITIONAL_TRAVEL_PAYMENT"/>
            <xs:enumeration value="MEETINGS_ATTENDED"/>
            <xs:enumeration value="MEDICAL_REPORTS_CLAIMED"/>
            <xs:enumeration value="DESI_ACC_REP"/>
            <xs:enumeration value="MHT_REF_NUMBER"/>
            <xs:enumeration value="STAGE_REACHED"/>
            <xs:enumeration value="FOLLOW_ON_WORK"/>
            <xs:enumeration value="NATIONAL_REF_MECHANISM_ADVICE"/>
            <xs:enumeration value="EXEMPTION_CRITERIA_SATISFIED"/>
            <xs:enumeration value="EXCL_CASE_FUNDING_REF"/>
            <xs:enumeration value="NO_OF_CLIENTS"/>
            <xs:enumeration value="NO_OF_SURGERY_CLIENTS"/>
            <xs:enumeration value="IRC_SURGERY"/>
            <xs:enumeration value="SURGERY_DATE"/>
            <xs:enumeration value="LINE_NUMBER"/>
            <xs:enumeration value="CRIME_MATTER_TYPE"/>
            <xs:enumeration value="FEE_SCHEME"/>
            <xs:enumeration value="REP_ORDER_DATE"/>
            <xs:enumeration value="NO_OF_SUSPECTS"/>
            <xs:enumeration value="NO_OF_POLICE_STATION"/>
            <xs:enumeration value="POLICE_STATION"/>
            <xs:enumeration value="DSCC_NUMBER"/>
            <xs:enumeration value="MAAT_ID"/>
            <xs:enumeration value="DUTY_SOLICITOR"/>
            <xs:enumeration value="YOUTH_COURT"/>
            <xs:enumeration value="SCHEME_ID"/>
            <xs:enumeration value="NUMBER_OF_MEDIATION_SESSIONS"/>
            <xs:enumeration value="MEDIATION_TIME"/>
            <xs:enumeration value="OUTREACH"/>
            <xs:enumeration value="REFERRAL"/>
            <xs:enumeration value="CLIENT_LEGALLY_AIDED"/>
            <xs:enumeration value="CLIENT2_FORENAME"/>
            <xs:enumeration value="CLIENT2_SURNAME"/>
            <xs:enumeration value="CLIENT2_DATE_OF_BIRTH"/>
            <xs:enumeration value="CLIENT2_UCN"/>
            <xs:enumeration value="CLIENT2_POST_CODE"/>
            <xs:enumeration value="CLIENT2_GENDER"/>
            <xs:enumeration value="CLIENT2_ETHNICITY"/>
            <xs:enumeration value="CLIENT2_DISABILITY"/>
            <xs:enumeration value="CLIENT2_LEGALLY_AIDED"/>
            <xs:enumeration value="UNIQUE_CASE_ID"/>
            <xs:enumeration value="STANDARD_FEE_CAT"/>
            <xs:enumeration value="CLIENT2_POSTAL_APPL_ACCP"/>
            <xs:enumeration value="COSTS_DAMAGES_RECOVERED"/>
            <xs:enumeration value="ELIGIBLE_CLIENT_INDICATOR"/>
            <xs:enumeration value="COURT_LOCATION_HPCDS"/>
            <xs:enumeration value="LOCAL_AUTHORITY_NUMBER"/>
            <xs:enumeration value="PA_NUMBER"/>
            <xs:enumeration value="EXCESS_TRAVEL_COSTS"/>
            <xs:enumeration value="MED_CONCLUDED_DATE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonBlankString">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\S.*"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- ========================= -->
    <!-- Root element              -->
    <!-- ========================= -->
    <xs:element name="submission">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="office">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="schedule" type="schedule"/>
                        </xs:sequence>
                        <xs:attribute name="account" type="officeAccountNumber" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="schemaLocation" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- ========================= -->
    <!-- Core types                -->
    <!-- ========================= -->
    <xs:complexType name="schedule">
        <xs:sequence>
            <xs:element name="outcome" type="outcome" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="newMatterStarts" type="newMatterStarts" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="immigrationCLR" type="immigrationCLR" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="areaOfLaw" type="areaOfLaw" use="required"/>
        <xs:attribute name="submissionPeriod" type="submissionPeriod" use="required"/>
        <xs:attribute name="scheduleNum" type="scheduleNumber" use="required"/>
    </xs:complexType>

    <xs:complexType name="outcome">
        <xs:sequence>
            <xs:element name="outcomeItem" type="outcomeItem" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="matterType" type="nonBlankString" use="required"/>
    </xs:complexType>

    <xs:complexType name="outcomeItem">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="outcomeItemName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="newMatterStarts">
        <xs:sequence>
            <xs:element name="matterStart"
                        type="matterStartCode"
                        maxOccurs="5"/>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="primaryMatterStartCode">
        <xs:restriction base="xs:string">
            <!-- MD codes -->
            <xs:enumeration value="MDCS"/>
            <xs:enumeration value="MDCC"/>
            <xs:enumeration value="MDPS"/>
            <xs:enumeration value="MDPC"/>
            <xs:enumeration value="MDAS"/>
            <xs:enumeration value="MDAC"/>

            <!-- Area codes -->
            <xs:enumeration value="AAP"/>
            <xs:enumeration value="COM"/>
            <xs:enumeration value="CON"/>
            <xs:enumeration value="DEB"/>
            <xs:enumeration value="EDU"/>
            <xs:enumeration value="EMP"/>
            <xs:enumeration value="ELA"/>
            <xs:enumeration value="HOU"/>
            <xs:enumeration value="IMMAS"/>
            <xs:enumeration value="IMMOT"/>
            <xs:enumeration value="MAT"/>
            <xs:enumeration value="MED"/>
            <xs:enumeration value="MHE"/>
            <xs:enumeration value="MSC"/>
            <xs:enumeration value="PI"/>
            <xs:enumeration value="PUB"/>
            <xs:enumeration value="WB"/>
            <xs:enumeration value="DISC"/>

            <!-- Optional other matter start codes -->
            <xs:enumeration value="SCHEDULE_REF"/>
            <xs:enumeration value="PROCUREMENT_AREA"/>
            <xs:enumeration value="ACCESS_POINT"/>
            <xs:enumeration value="DELIVERY_LOCATION"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="matterStartCode">
        <xs:simpleContent>
            <xs:extension base="nonBlankString">
                <xs:attribute name="code"
                              type="primaryMatterStartCode"
                              use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="immigrationCLR">
        <xs:sequence>
            <xs:element name="immCLRData" type="immCLRData" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="immCLRData">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="code" type="upperSnake" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== ministryofjustice/laa-data-claims-api/claims-data/service/src/test/resources/test_upload_files/xml/immigration_clr_with_leading_and_trailing_whitespaces.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<submission xsi:schemaLocation="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/ LSCSMSBulkLoadSchemaV3.xsd"
            xmlns="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <office account="2P554H">
        <schedule submissionPeriod="JAN-2010" areaOfLaw="CRIME LOWER" scheduleNum="ABC/20000L/10">
            <outcome matterType="INVC">
                <outcomeItem name="CLIENT_SURNAME">Client surname</outcomeItem>
                <outcomeItem name="CLIENT_FORENAME">Client forename</outcomeItem>
                <outcomeItem name="GENDER">M</outcomeItem>
                <outcomeItem name="ETHNICITY">00</outcomeItem>
                <outcomeItem name="DISABILITY">NCD</outcomeItem>
                <outcomeItem name="UFN">300101/001</outcomeItem>
                <outcomeItem name="OUTCOME_CODE">AB01</outcomeItem>
                <outcomeItem name="CRIME_MATTER_TYPE">3</outcomeItem>
                <outcomeItem name="PROFIT_COST">1.01</outcomeItem>
                <outcomeItem name="DISBURSEMENTS_AMOUNT">1.02</outcomeItem>
                <outcomeItem name="TRAVEL_COSTS">1.03</outcomeItem>
                <outcomeItem name="TRAVEL_WAITING_COSTS">1.04</outcomeItem>
                <outcomeItem name="VAT_INDICATOR">Y</outcomeItem>
                <outcomeItem name="DISBURSEMENTS_VAT">0.90</outcomeItem>
                <outcomeItem name="WORK_CONCLUDED_DATE">01/01/2010</outcomeItem>
                <outcomeItem name="NO_OF_SUSPECTS">1</outcomeItem>
                <outcomeItem name="NO_OF_POLICE_STATION">1</outcomeItem>
                <outcomeItem name="POLICE_STATION">AB001</outcomeItem>
                <outcomeItem name="DSCC_NUMBER">100000000A</outcomeItem>
                <outcomeItem name="DUTY_SOLICITOR">N</outcomeItem>
                <outcomeItem name="YOUTH_COURT">N</outcomeItem>
                <outcomeItem name="SCHEME_ID">2001</outcomeItem>
            </outcome>
            <immigrationCLR>
                <immCLRData code="CLR_FIELD"> value </immCLRData>
                <immCLRData code="ANOTHER_FIELD"> 12345 </immCLRData>
            </immigrationCLR>
            <immigrationCLR>
                <immCLRData code="CLR_FIELD2"> value2 </immCLRData>
                <immCLRData code="ANOTHER_FIELD2"> 123456 </immCLRData>
            </immigrationCLR>
        </schedule>
    </office>
</submission>

=== ministryofjustice/laa-data-claims-api/claims-data/service/src/integrationTest/resources/test_upload_files/xml/outcomes_unicode_names.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<submission xsi:schemaLocation="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/ LSCSMSBulkLoadSchemaV3.xsd"
    xmlns="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <office account="0U099L">
        <schedule submissionPeriod="APR-2021" areaOfLaw="LEGAL HELP" scheduleNum="0U099L/LEGAL_HELP">
            <outcome matterType="IALB:IFRA">
                <outcomeItem name="CASE_REF_NUMBER">TestCaseRef</outcomeItem>
                <outcomeItem name="CASE_START_DATE">07/07/2022</outcomeItem>
                <outcomeItem name="CASE_ID">001</outcomeItem>
                <outcomeItem name="UFN">070722/001</outcomeItem>
                <outcomeItem name="PROCUREMENT_AREA">PA00136</outcomeItem>
                <outcomeItem name="ACCESS_POINT">AP00137</outcomeItem>
                <outcomeItem name="CLIENT_FORENAME">Siân</outcomeItem>
                <outcomeItem name="CLIENT_SURNAME">O’Brien</outcomeItem>
                <outcomeItem name="CLIENT2_SURNAME">Łukasz</outcomeItem>
                <outcomeItem name="CLIENT_DATE_OF_BIRTH">14/09/1962</outcomeItem>
                <outcomeItem name="UCN">14091962/T/PERS</outcomeItem>
                <outcomeItem name="GENDER">M</outcomeItem>
                <outcomeItem name="ETHNICITY">99</outcomeItem>
                <outcomeItem name="DISABILITY">UKN</outcomeItem>
                <outcomeItem name="CLIENT_POST_CODE">SW1H 9EA</outcomeItem>
                <outcomeItem name="WORK_CONCLUDED_DATE">21/10/2022</outcomeItem>
                <outcomeItem name="PROFIT_COST">228.00</outcomeItem>
                <outcomeItem name="OUTCOME_CODE">IX</outcomeItem>
            </outcome>
        </schedule>
    </office>
</submission>

=== ministryofjustice/laa-data-claims-api/claims-data/service/src/test/resources/test_upload_files/xml/outcomes_with_all_possible_fields.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<submission xsi:schemaLocation="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/ LSCSMSBulkLoadSchemaV3.xsd"
	xmlns="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<office account="AB1234">
		<schedule submissionPeriod="JAN-2010" areaOfLaw="CRIME LOWER" scheduleNum="SCH001">
			<outcome matterType="INVC">
                <outcomeItem name="FEE_CODE">FC01</outcomeItem>
                <outcomeItem name="CASE_REF_NUMBER">CRN123456</outcomeItem>
                <outcomeItem name="CASE_START_DATE">2026-01-05</outcomeItem>
                <outcomeItem name="CASE_ID">CID7890</outcomeItem>
                <outcomeItem name="CASE_STAGE_LEVEL">1</outcomeItem>
                <outcomeItem name="UFN">010126/001</outcomeItem>
                <outcomeItem name="PROCUREMENT_AREA">PA1</outcomeItem>
                <outcomeItem name="ACCESS_POINT">ONLINE</outcomeItem>
                <outcomeItem name="CLIENT_FORENAME">John</outcomeItem>
                <outcomeItem name="CLIENT_SURNAME">Smith</outcomeItem>
                <outcomeItem name="CLIENT_DATE_OF_BIRTH">1985-06-15</outcomeItem>
                <outcomeItem name="UCN">UCN12345</outcomeItem>
                <outcomeItem name="CLA_REF_NUMBER">CLA999</outcomeItem>
                <outcomeItem name="CLA_EXEMPTION">N</outcomeItem>
                <outcomeItem name="GENDER">M</outcomeItem>
                <outcomeItem name="ETHNICITY">A1</outcomeItem>
                <outcomeItem name="DISABILITY">N</outcomeItem>
                <outcomeItem name="CLIENT_POST_CODE">B28 0XB</outcomeItem>
                <outcomeItem name="WORK_CONCLUDED_DATE">2026-01-20</outcomeItem>
                <outcomeItem name="ADVICE_TIME">120</outcomeItem>
                <outcomeItem name="TRAVEL_TIME">30</outcomeItem>
                <outcomeItem name="WAITING_TIME">15</outcomeItem>
                <outcomeItem name="PROFIT_COST">250.00</outcomeItem>
                <outcomeItem name="VALUE_OF_COSTS">300.00</outcomeItem>
                <outcomeItem name="DISBURSEMENTS_AMOUNT">50.00</outcomeItem>
                <outcomeItem name="COUNSEL_COST">100.00</outcomeItem>
                <outcomeItem name="DISBURSEMENTS_VAT">10.00</outcomeItem>
                <outcomeItem name="TRAVEL_WAITING_COSTS">40.00</outcomeItem>
                <outcomeItem name="VAT_INDICATOR">Y</outcomeItem>
                <outcomeItem name="LONDON_NONLONDON_RATE">NON_LONDON</outcomeItem>
                <outcomeItem name="CLIENT_TYPE">ADULT</outcomeItem>
                <outcomeItem name="TOLERANCE_INDICATOR">N</outcomeItem>
                <outcomeItem name="TRAVEL_COSTS">20.00</outcomeItem>
                <outcomeItem name="OUTCOME_CODE">SUCCESS</outcomeItem>
                <outcomeItem name="LEGACY_CASE">N</outcomeItem>
                <outcomeItem name="CLAIM_TYPE">STANDARD</outcomeItem>
                <outcomeItem name="ADJOURNED_HEARING_FEE">0.00</outcomeItem>
                <outcomeItem name="TYPE_OF_ADVICE">GENERAL</outcomeItem>
                <outcomeItem name="POSTAL_APPL_ACCP">N</outcomeItem>
                <outcomeItem name="SCHEDULE_REF">REF123</outcomeItem>
                <outcomeItem name="CMRH_ORAL">N</outcomeItem>
                <outcomeItem name="CMRH_TELEPHONE">Y</outcomeItem>
                <outcomeItem name="AIT_HEARING_CENTRE">BIRMINGHAM</outcomeItem>
                <outcomeItem name="SUBSTANTIVE_HEARING">Y</outcomeItem>
                <outcomeItem name="HO_INTERVIEW">N</outcomeItem>
                <outcomeItem name="HO_UCN">HO12345</outcomeItem>
                <outcomeItem name="TRANSFER_DATE">2026-01-10</outcomeItem>
                <outcomeItem name="DETENTION_TRAVEL_WAITING_COSTS">0.00</outcomeItem>
                <outcomeItem name="DELIVERY_LOCATION">OFFICE</outcomeItem>
                <outcomeItem name="PRIOR_AUTHORITY_REF">PAUTH001</outcomeItem>
                <outcomeItem name="JR_FORM_FILLING">N</outcomeItem>
                <outcomeItem name="ADDITIONAL_TRAVEL_PAYMENT">0.00</outcomeItem>
                <outcomeItem name="MEETINGS_ATTENDED">3</outcomeItem>
                <outcomeItem name="MEDICAL_REPORTS_CLAIMED">1</outcomeItem>
                <outcomeItem name="DESI_ACC_REP">N</outcomeItem>
                <outcomeItem name="MHT_REF_NUMBER">MHT123</outcomeItem>
                <outcomeItem name="STAGE_REACHED">FINAL</outcomeItem>
                <outcomeItem name="FOLLOW_ON_WORK">N</outcomeItem>
                <outcomeItem name="NATIONAL_REF_MECHANISM_ADVICE">N</outcomeItem>
                <outcomeItem name="EXEMPTION_CRITERIA_SATISFIED">Y</outcomeItem>
                <outcomeItem name="EXCL_CASE_FUNDING_REF">ECF001</outcomeItem>
                <outcomeItem name="NO_OF_CLIENTS">1</outcomeItem>
                <outcomeItem name="NO_OF_SURGERY_CLIENTS">0</outcomeItem>
                <outcomeItem name="IRC_SURGERY">N</outcomeItem>
                <outcomeItem name="SURGERY_DATE">2026-01-15</outcomeItem>
                <outcomeItem name="LINE_NUMBER">1</outcomeItem>
                <outcomeItem name="CRIME_MATTER_TYPE">TYPE1</outcomeItem>
                <outcomeItem name="FEE_SCHEME">FS1</outcomeItem>
                <outcomeItem name="REP_ORDER_DATE">2026-01-03</outcomeItem>
                <outcomeItem name="NO_OF_SUSPECTS">1</outcomeItem>
                <outcomeItem name="NO_OF_POLICE_STATION">1</outcomeItem>
                <outcomeItem name="POLICE_STATION">Solihull</outcomeItem>
                <outcomeItem name="DSCC_NUMBER">DSCC123</outcomeItem>
                <outcomeItem name="MAAT_ID">MAAT456</outcomeItem>
                <outcomeItem name="DUTY_SOLICITOR">Y</outcomeItem>
                <outcomeItem name="YOUTH_COURT">N</outcomeItem>
                <outcomeItem name="SCHEME_ID">SCHM1</outcomeItem>
                <outcomeItem name="NUMBER_OF_MEDIATION_SESSIONS">2</outcomeItem>
                <outcomeItem name="MEDIATION_TIME">180</outcomeItem>
                <outcomeItem name="OUTREACH">N</outcomeItem>
                <outcomeItem name="REFERRAL">SELF</outcomeItem>
                <outcomeItem name="CLIENT_LEGALLY_AIDED">Y</outcomeItem>
                <outcomeItem name="CLIENT2_FORENAME">Jane</outcomeItem>
                <outcomeItem name="CLIENT2_SURNAME">Smith</outcomeItem>
                <outcomeItem name="CLIENT2_DATE_OF_BIRTH">1990-04-20</outcomeItem>
                <outcomeItem name="CLIENT2_UCN">UCN67890</outcomeItem>
                <outcomeItem name="CLIENT2_POST_CODE">B90 3AA</outcomeItem>
                <outcomeItem name="CLIENT2_GENDER">F</outcomeItem>
                <outcomeItem name="CLIENT2_ETHNICITY">B2</outcomeItem>
                <outcomeItem name="CLIENT2_DISABILITY">N</outcomeItem>
                <outcomeItem name="CLIENT2_LEGALLY_AIDED">Y</outcomeItem>
                <outcomeItem name="UNIQUE_CASE_ID">UCID123456</outcomeItem>
                <outcomeItem name="STANDARD_FEE_CAT">CAT1</outcomeItem>
                <outcomeItem name="CLIENT2_POSTAL_APPL_ACCP">N</outcomeItem>
                <outcomeItem name="COSTS_DAMAGES_RECOVERED">0.00</outcomeItem>
                <outcomeItem name="ELIGIBLE_CLIENT_INDICATOR">Y</outcomeItem>
                <outcomeItem name="COURT_LOCATION_HPCDS">BIRMINGHAM</outcomeItem>
                <outcomeItem name="LOCAL_AUTHORITY_NUMBER">LA123</outcomeItem>
                <outcomeItem name="PA_NUMBER">PA999</outcomeItem>
                <outcomeItem name="EXCESS_TRAVEL_COSTS">0.00</outcomeItem>
                <outcomeItem name="MED_CONCLUDED_DATE">2026-01-25</outcomeItem>
			</outcome>
		</schedule>
	</office>
</submission>

=== ministryofjustice/laa-data-claims-api/bruno/test-assets/EV-CLM-053.1_outcome_code_crime_valid_code_scenario_it_tests.xml
<?xml version='1.0' encoding='UTF-8'?>
<submission xmlns="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.legalservices.gov.uk/sms/ActivityManagement/XMLSchema/ LSCSMSBulkLoadSchemaV3.xsd">
  <office account="0P322F">
    <schedule submissionPeriod="OCT-2025" areaOfLaw="CRIME LOWER" scheduleNum="000123/EV0531/01">
      <outcome matterType="INVC">
        <outcomeItem name="FEE_CODE">INVC</outcomeItem>
        <outcomeItem name="CASE_REF_NUMBER">EV0531CR-OUTC</outcomeItem>
        <outcomeItem name="UFN">101224/931</outcomeItem>
        <outcomeItem name="CASE_START_DATE">08/11/2025</outcomeItem>
        <outcomeItem name="WORK_CONCLUDED_DATE">10/11/2025</outcomeItem>
        <outcomeItem name="CLIENT_FORENAME">Alice</outcomeItem>
        <outcomeItem name="CLIENT_SURNAME">EV0531CR-OUTC</outcomeItem>
        <outcomeItem name="CLIENT_DATE_OF_BIRTH">01/01/1990</outcomeItem>
        <outcomeItem name="CLIENT_POST_CODE">SW1H 9EA</outcomeItem>
        <outcomeItem name="GENDER">F</outcomeItem>
        <outcomeItem name="ETHNICITY">02</outcomeItem>
        <outcomeItem name="OUTCOME_CODE">CN02</outcomeItem>
        <outcomeItem name="CRIME_MATTER_TYPE">03</outcomeItem>
        <outcomeItem name="STAGE_REACHED">INVA</outcomeItem>
        <outcomeItem name="PROFIT_COST">150.00</outcomeItem>
        <outcomeItem name="DISBURSEMENTS_AMOUNT">25.00</outcomeItem>
        <outcomeItem name="TRAVEL_COSTS">10.00</outcomeItem>
        <outcomeItem name="TRAVEL_WAITING_COSTS">5.00</outcomeItem>
        <outcomeItem name="VAT_INDICATOR">Y</outcomeItem>
        <outcomeItem name="DISBURSEMENTS_VAT">5.00</outcomeItem>
        <outcomeItem name="NO_OF_SUSPECTS">1</outcomeItem>
        <outcomeItem name="NO_OF_POLICE_STATION">1</outcomeItem>
        <outcomeItem name="POLICE_STATION">NE001</outcomeItem>
        <outcomeItem name="DSCC_NUMBER">EV0531DS01</outcomeItem>
        <outcomeItem name="DUTY_SOLICITOR">N</outcomeItem>
        <outcomeItem name="YOUTH_COURT">N</outcomeItem>
        <outcomeItem name="SCHEME_ID">1013</outcomeItem>
      </outcome>
    </schedule>
  </office>
</submission>
